public enum PersonelDurumu {
    AKTIF_GOREVDE,
    TEDAVI_GORUYOR,
    SEHIT,
    EMEKLI,
    ACIGA_ALINMIS,
    GOREVDEN_AYRILMIS,
    GOREVDEN_ATILMIS,
    ISTIFA_SURECINDE,
    ISTIFA_ONAYLANMIS
}
